package com.ds.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CONVERSATION".
 */
public class Conversation {

    private Long id;
    private Integer memberId;
    private String memberName;
    private java.util.Date chatTime;
    private String memberAvater;
    private String lastContent;
    private Boolean isRead;

    public Conversation() {
    }

    public Conversation(Long id) {
        this.id = id;
    }

    public Conversation(Long id, Integer memberId, String memberName, java.util.Date chatTime, String memberAvater, String lastContent, Boolean isRead) {
        this.id = id;
        this.memberId = memberId;
        this.memberName = memberName;
        this.chatTime = chatTime;
        this.memberAvater = memberAvater;
        this.lastContent = lastContent;
        this.isRead = isRead;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getMemberId() {
        return memberId;
    }

    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    public String getMemberName() {
        return memberName;
    }

    public void setMemberName(String memberName) {
        this.memberName = memberName;
    }

    public java.util.Date getChatTime() {
        return chatTime;
    }

    public void setChatTime(java.util.Date chatTime) {
        this.chatTime = chatTime;
    }

    public String getMemberAvater() {
        return memberAvater;
    }

    public void setMemberAvater(String memberAvater) {
        this.memberAvater = memberAvater;
    }

    public String getLastContent() {
        return lastContent;
    }

    public void setLastContent(String lastContent) {
        this.lastContent = lastContent;
    }

    public Boolean getIsRead() {
        return isRead;
    }

    public void setIsRead(Boolean isRead) {
        this.isRead = isRead;
    }

}
